### ISSUE TITLE
Incomplete outline for ColumnTypes.cpp (in Haiku source)

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#376] opened 2024-05-02 12:40 UTC
If you open `/src/kits/interface/ColumnTypes.cpp` in the Haiku source tree, you only get one entry in the Outline pane: **gSystemCatalog**

Something's not right...

**Comment by nexus6-haiku** [comment] 2024-05-04 14:05
Has the compile db been generated?

**Comment by humdingerb** [comment] 2024-05-04 17:52
How can I tell?
I just did a "Open project..." and opened the `/src/kits/interface` folder. Then opened the file `ColumnTypes.cpp`.

**Comment by nexus6-haiku** [comment] 2024-05-04 21:18
Just a bit of context on how clangd (the Language Server) works. It uses the AST produced by clang which in turn needs to know of to compile the translation units that are part of a C++ project. The compile db is a list of the options and parameters needed to compile the project and can be produced in different ways. We explain this in Configuring-clangd-lsp.md. Without it clangd may have an incomplete view of the entire AST and fail to resolve some symbols.
Now, I'm just trying to figure whether this is your case.

**Comment by humdingerb** [comment] 2024-05-05 05:29
FWIW, I don't see a "compile_commands.json" or "config.yaml" in any settings folder or project...

In any case, the outline works for other files in the same folder...

**Comment by nexus6-haiku** [comment] 2024-05-06 14:34
![2024-05-06_16-32](https://github.com/Genio-The-Haiku-IDE/Genio/assets/105149392/c1924902-eec5-4907-8bba-6853a6efe670)

I open a project pointing to `/src/kits/interface/`, then I open whatever file and get the symbols within. Being them internal symbols in the file itself, I presume this would be quite trivial for clangd without requiring the compile db.
Are these steps the same for you?

**Comment by nexus6-haiku** [comment] 2024-05-07 14:17
Are you on LLVM16 or 17?

**Comment by humdingerb** [comment] 2024-05-07 15:38
I got these:

llvm12_libs-12.0.1-8-x86_64.hpkg
llvm17_clang-17.0.6-1-x86_64.hpkg
llvm17_libs-17.0.6-1-x86_64.hpkg

**Comment by Freaxed** [comment] 2024-05-08 19:53
I could not reproduce.. if you have time, please run genio with low/off log level but with Trace log level for LSP.
Open just the header file to keep the log noise at minimum.
Thanks

**Comment by humdingerb** [comment] 2024-05-09 06:04
> Open just the header file to keep the log noise at minimum.

To clarify, the outline issue described happens when opening `/src/kits/interface/ColumnTypes.cpp`, not its header file.

Here are the logs when opening
* `/src/kits/interface/ColumnTypes.cpp`: [log_ColumnTypes.txt](https://github.com/Genio-The-Haiku-IDE/Genio/files/15258168/log_ColumnTypes.txt) (the problem)
* `/src/kits/interface/Control.cpp`: [log_Control.txt](https://github.com/Genio-The-Haiku-IDE/Genio/files/15258177/log_Control.txt)  (working, for comparison)

**Comment by lonemadmax** [comment] 2024-05-09 15:54
Not a clangd or LSP expert here, or even C++, so I may be talkng nonsense, but maybe there's nothing else because it can't tell whether they are class methods or namespaced functions or something else due to lack of declarations? For Control.cpp it gets the header file with the declarations from the system include path, but for ColumnTypes.cpp it can't because it's in private and that's not in the list (and without the compile db it doesn't know where else to look for it). Just for testing, could you try copying ColumntTypes.h in src/kits/interface?

**Comment by jackburton79** [comment] 2024-05-09 15:57
Ah sure! This might well be! That would also explain the different behaviour on different systems: maybe @Freaxed and @nexus6-haiku configured clangd differently by adding those paths in the configuration?

**Comment by Freaxed** [comment] 2024-05-09 16:03
I agree, this could explain the behaviour. Anyway, by looking at the logs, Genio is correctly showing the only symbol sent by clangd (gSystemCatalog).

**Comment by humdingerb** [comment] 2024-05-09 16:15
> Just for testing, could you try copying ColumntTypes.h in src/kits/interface?

Indeed this 'fixes' my outline issue. Nice work, Sherlock Máximo!
I guess there's nothing Genio can do in these cases and this is a closable non-issue=

**Comment by jackburton79** [comment] 2024-05-22 07:59
I guess that would work if we added the private headers folder into the clangd configuration, @Freaxed ?
Unfortunately we can't provide that file on installation, right ?

**Comment by Freaxed** [comment] 2024-05-22 08:09
AFAIK there are 3 ways to provide a configuration parameter: by command
line, by local project file and by user settings file.
We should investigate a bit on command line options or maybe we could
create/update the user settings file.


Il giorno mer 22 mag 2024 alle ore 10:00 Stefano Ceccherini <
***@***.***> ha scritto:

**Comment by lonemadmax** [comment] 2024-05-22 15:07
Is it worth it, though? Next thing is a header that is in the project but not in the installation. Or one that is different enough to cause confusion.

**Comment by jackburton79** [comment] 2024-05-22 17:16
Headers in the project folder are on thing, but would be nice to provide a nice experience out of the box, including also private and shared haiku headers, at least. On the other hand, the current situation isnt that bad and more advanced users should learn how to configure clangd and do themselves

**Comment by jackburton79** [comment] 2024-05-23 09:59
Anyway, let's close this for now.

**Closed by jackburton79** 2024-05-23 09:59 UTC
