### ISSUE TITLE
Rare bug replaces first lines in opened files with garbage log text

### ISSUE THREAD

**Issue by cafeina-software** [Genio-The-Haiku-IDE/Genio#272] opened 2024-01-07 00:28 UTC
I still don't know how this is triggered or where is the bug, but rarely when editing and saving or compiling, the first lines of the files being edited are overwritten with garbage text. This is not visible in Genio editor, but can be viewed by opening the file with another editor. One can also realize there is something wrong with the source code when compilation is tried: an error in code will appear in output pane.

The garbage text is something like this:

```
{T} IconCache: [text/source-code] - [main.cpp]
{T} IconCache: return icon from cache for text/source-code
// original source code follows from here...
```

**Comment by jackburton79** [comment] 2024-01-07 08:51
I remember this one longo time ago, but we haven't been seeing this for a while.
I see you have log level set to trace: is this a conscious choice?

**Comment by Freaxed** [comment] 2024-01-07 09:04
Would also be nice to know the haiku revision and architecture
(32bit/64bit, VM or real hardware).

Thanks!

Il giorno dom 7 gen 2024 alle 09:51 Stefano Ceccherini <
***@***.***> ha scritto:

**Comment by fuckyourselfup** [comment] 2024-01-08 00:58
Environment:
- Haiku x86_64, hrev57499
- Running on real hardware.

About the log level=trace: it was a semi-conscious choice, made while I was translating the app. I was checking all the menus, drop-down lists, etc., to know if they were translatable and if so, if the translation was properly saved and displayed, and I could have left this option enabled just because I forgot to set it back to its default value.

**Comment by Freaxed** [comment] 2024-01-08 15:45
We did some fixes that could potentially solve also this (https://github.com/Genio-The-Haiku-IDE/Genio/pull/275) 

Are you able to update to the latest 'main' version and test if it reproduce again?

Thanks!

**Comment by fuckyourselfup** [comment] 2024-01-22 23:42
Although I still don't really know how that bug could be triggered, with #275 it hasn't yet appeared.

**Comment by jackburton79** [comment] 2024-03-31 20:55
> Although I still don't really know how that bug could be triggered, with #275 it hasn't yet appeared.

Did you manage to reproduce this ?

**Comment by jackburton79** [comment] 2024-04-14 14:37
I'd close this. Let's reopen if it happens again.

**Closed** 2024-04-14 14:37 UTC
Labels: bug
