### ISSUE TITLE
Genio settings: "Enable brace matching" not working

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#361] opened 2024-04-23 18:03 UTC
Does this setting work?
It appears that no matter if the checkbox is ticked or not, setting the cursor on a brace will highlight the corresponding brace.

Or is that setting supposed to control something else.
Personally, I cannot imagine a reason to deactivate this highlighting...

**Comment by jackburton79** [comment] 2024-04-23 18:09
Yes, it should work like that. Maybe it's not applied live (due to some missing code, or a regression).
I'll have a look

**Comment by jackburton79** [comment] 2024-04-23 19:59
Well, it seems the "brace_match" settings is never checked anywere.
Now, I'd agree with you that I cannot image a reason to deactivate this highlighting, but since we have also an option to disable syntax highlighting, 
Who knows, maybe we'll end up removing the setting, but since it's there, I guess it would be correct to fix this

**Comment by Freaxed** [comment] 2024-06-14 10:01
fixed with df772d270f81d62c2d8db5f30e4f4468b3a48fb3

**Closed by Freaxed** 2024-06-14 10:01 UTC
Labels: bug
