### ISSUE TITLE
Replace previous occurence doesn't find occurence

### ISSUE THREAD

**Issue by tmtfx** [Genio-The-Haiku-IDE/Genio#301] opened 2024-01-18 19:22 UTC
With "replace and find previous" button the string is replaced but it doesn't look for a previous occurence.
The occurence can still be found with "find previous" button

**Comment by Freaxed** [comment] 2024-01-23 13:07
I'm not able to reproduce. Do you have an example? (a file and a replace term)
What Genio version are you using? On virtual machine or real hardware? x64 architecture?
Thanks!

**Comment by tmtfx** [comment] 2024-01-23 20:06
Me too. It happened when I filed the issue, but now it works as it is intended. Genio is being used in a virtual machine on Haiku 32 bit. The version... don't remember if it was 2.0 (now I'm using 2.1). Please close this issue, if it happens again I'll file a new issue

**Comment by Freaxed** [comment] 2024-01-23 20:44
The bug was present in version 2.0 and fixed in version 2.1.
I'm closing this for now.

**Closed** 2024-01-23 20:44 UTC
