### ISSUE TITLE
Outline: Symbol name sometimes doesn't update after rename in editor

### ISSUE THREAD

**Issue by humdingerb** [Genio-The-Haiku-IDE/Genio#353] opened 2024-04-21 09:28 UTC
I've been playing around with the "Rename symbol" of the Outline context menu.

It always succeeds in renaming the e.g. function name in the file in the editor. But sometimes, the new symbol name in the Outline list isn't updated. Same when changing the function name in the editor: sometimes the entry in the Outline list isnt updated.

So I understand the function correctly: "Rename symbol" renames the symbol in all currently open files, right.
For example, if I rename the variable fItemCount in SourceFile.h and SourceFile.cpp that uses it happens to be open, fItemCount gets renamed there too. If the .cpp file is not open, it's not renamed.
Should in that case an alert pop up, saying something like:

```
The symbol '%symbol_name%' is also used in these files:
* file1
* file2
* file3
Rename the symbol there too?

              [Cancel] [Open files] [Rename all]
```

Or is this not possible?
Or even: Doesn't renaming a symbol imply that it always should be renamed in all files of a project? And only pop an alert if the new name collided with an existing symbol name?

[The above doesn't really fit to the initially reported issue. Should I post it to https://github.com/Genio-The-Haiku-IDE/Genio/discussions instead? Do you guys read those? :) ]

**Comment by nexus6-haiku** [comment] 2024-04-21 11:50
Rename is evaluated by the LSP that hands over the files and the ranges to the editor which actually performs the edit.
A rename is supposed to happen also when the file is not opened, Genio opens it and does the change automatically.
If it does not happen is clearly a bug.
We need the exact steps to reproduce it, including the affected project.
The benefit of symbol renaming is that the user does not have to take care of doing anything, it should happen automatically. If you happen to use IDEs like Visual Studio, Visual Studio Code or extensions like ReSharper (both C# and C++ flavours) you would experience the same behaviour.
PS: We read everything including the discussion section! But this looks like an issue to me

**Comment by nexus6-haiku** [comment] 2024-04-24 22:22
> Should in that case an alert pop up, saying something like:
> 
> ```
> The symbol '%symbol_name%' is also used in these files:
> * file1
> * file2
> * file3
> Rename the symbol there too?
> 
>               [Cancel] [Open files] [Rename all]
> ```

I don't think it would be easy or even possible to detect the files affected beforehand for a number of reasons, the main one is that LSP is completely asynchronous.
I'm closing this for now unless we find a way around it.

**Closed by nexus6-haiku** 2024-04-24 22:22 UTC

**Comment by jackburton79** [comment] 2024-04-25 10:06
> My expectation, in case of name collision, is that LSP fails to provide the
> renaming instructions. Not sure if we are handling the error properly.
> 
Same expectation here. Definitely a thing to test

**Comment by humdingerb** [comment] 2024-04-25 13:06
Agreed. Only show an alert if namess clash, if possible.

I cannot seem to reproduce the original issue "Symbol name sometimes doesn't update after rename in editor", so it's just as well this ticket got closed.

I have another symbol-renaming issue though... :)
I'll open a discussion post on that.
